In [2]:
class TicTacToe:
    def __init__(self):
        self.board = [[' ' for _ in range(3)] for _ in range(3)]

    def display_board(self):
        for row in self.board:
            print('|'.join(row))
            print("-----")
        print()    
        print()    

    def is_winner(self, player):
        # Check rows
        for row in self.board:
            if all(cell == player for cell in row):
                return True
        # Check columns
        for col in range(3):
            if all(self.board[row][col] == player for row in range(3)):
                return True
        # Check diagonals
        if all(self.board[i][i] == player for i in range(3)) or \
                all(self.board[i][2 - i] == player for i in range(3)):
            return True
        return False

    def is_full(self):
        for row in self.board:
            if ' ' in row:
                return False
        return True

    def make_move(self, row, col, player):
        if self.board[row][col] == ' ':
            self.board[row][col] = player
            return True
        return False

    def undo_move(self, row, col):
        self.board[row][col] = ' '

def alpha_beta_pruning(board, depth, alpha, beta, check_maximizing_player):
    if board.is_winner('X'):
        return -10 + depth, None
    elif board.is_winner('O'):
        return 10 - depth, None
    elif board.is_full():
        return 0, None

    if check_maximizing_player:
        max_eval = float('-inf')
        best_move = None
        for i in range(3):
            for j in range(3):
                if board.board[i][j] == ' ':
                    board.make_move(i, j, 'O')
                    eval, _ = alpha_beta_pruning(board, depth + 1, alpha, beta, False)
                    board.undo_move(i, j)
                    if eval > max_eval:
                        max_eval = eval
                        best_move = (i, j)
                    alpha = max(alpha, eval)
                    if beta <= alpha:
                        break
        return max_eval, best_move
    else:
        min_eval = float('inf')
        best_move = None
        for i in range(3):
            for j in range(3):
                if board.board[i][j] == ' ':
                    board.make_move(i, j, 'X')
                    eval, _ = alpha_beta_pruning(board, depth + 1, alpha, beta, True)
                    board.undo_move(i, j)
                    if eval < min_eval:
                        min_eval = eval
                        best_move = (i, j)
                    beta = min(beta, eval)
                    if beta <= alpha:
                        break
        return min_eval, best_move

def play_game():
    board = TicTacToe()
    while not board.is_winner('X') and not board.is_winner('O') and not board.is_full():
        
        board.display_board()

        if len([cell for row in board.board for cell in row if cell == ' ']) % 2 == 0:
            _, (row, col) = alpha_beta_pruning(board, 0, float('-inf'), float('inf'), True)
            print("AI's move \n")
            player = 'O'
        else:
            print("Player's Move\n")
            row = int(input("Enter row [0,1,2]: "))
            col = int(input("Enter column [0,1,2]: "))
            player = 'X'

        if board.make_move(row, col, player):
            if board.is_winner(player):
                board.display_board()
                print(f"{player} wins!")
                break
            elif board.is_full():
                board.display_board()
                print("It's a draw!")
                break
        else:
            print("Invalid move. Try again.")

if __name__ == "__main__":
    play_game()


 | | 
-----
 | | 
-----
 | | 
-----


Player's Move

X| | 
-----
 | | 
-----
 | | 
-----


AI's move 

X| | 
-----
 |O| 
-----
 | | 
-----


Player's Move

X| | 
-----
 |O| 
-----
 | |X
-----


AI's move 

X|O| 
-----
 |O| 
-----
 | |X
-----


Player's Move

X|O|X
-----
 |O| 
-----
 | |X
-----


AI's move 

X|O|X
-----
 |O| 
-----
 |O|X
-----


O wins!


In [5]:
class TicTacToe:

    def __init__(self):

        self.board = [ [' ' for _ in range(3) ] for _ in range(3) ]

    def display(self):
        
        for i in range(3):                
            print( '|'.join(self.board[i]) )
            print('-----')
        print()
        print()


    def is_winner(self, player):

        for i, row in enumerate(self.board):
            if all( cell == player for cell in row ):
                return True

        for col in range(3):
            if all( self.board[row][col] == player for row in range(3) ):
                return True

        if ( all( self.board[i][i] ==  player for i in range(3) ) or all( self.board[i][2-i] ==  player for i in range(3) ) ):
            return True

        return False


    def is_full(self):

        for i in range(3):
            for j in range(3):
                if self.board[i][j] == ' ':
                    return False
        
        return True


    def make_move(self, i, j, player):

        if self.board[i][j] == ' ' :
            self.board[i][j] = player
            return True
        return False


    def undo_move(self, i, j):
    
        self.board[i][j] = ' '


def AlphaBetaPruning(Board, depth, alpha, beta, maximizing):

    if Board.is_winner("X"):
        return -10 + depth, None
    elif Board.is_winner("O"):
        return 10 - depth, None
    elif Board.is_full():
        return 0, None

    if maximizing:

        max_eval = float('-inf')
        best_move = (0, 0)
        for i in range(3):
            for j in range(3):
                if Board.board[i][j] == ' ':
                    Board.make_move(i, j, 'O')
                    eval, _  = AlphaBetaPruning(Board, depth+1, alpha, beta, False)
                    Board.undo_move(i, j)

                    if (eval > max_eval ):
                        max_eval = eval
                        best_move = (i, j)

                    alpha = max(alpha, eval)
                    if alpha >= beta:
                        break
        
        return max_eval, best_move

    else:

        min_eval = float('inf')
        best_move = (0, 0)
        for i in range(3):
            for j in range(3):
                if Board.board[i][j] == ' ':
                    Board.make_move(i, j, 'X')
                    eval, _  = AlphaBetaPruning(Board, depth+1, alpha, beta, True)
                    Board.undo_move(i, j)

                    if (eval < min_eval ):
                        min_eval = eval
                        best_move = (i, j)

                    beta = min(beta, eval)
                    if alpha >= beta:
                        break
    
        return min_eval, best_move



def play_game():

    Board = TicTacToe()

    while not Board.is_winner('X') and not Board.is_winner('O') and not Board.is_full():

        Board.display()

        if ( len([cell for row in Board.board for cell in row if cell == ' ' ]) ) % 2 == 0:
            # AI Turn
            print("AI Turn: ")
            player = 'O'
            _ , (row, col) = AlphaBetaPruning(Board, 0, float('-inf'), float('inf'), True)


        else:
            print("Player Turn: ")
            row = int(input('Enter Row: '))
            col = int(input('Enter Col: '))
            player = 'X'
            
        if Board.make_move(row, col, player):
            if Board.is_winner("X"):
                print("Player Won")
                Board.display()
                break
            elif Board.is_winner("O"):
                print('AI Won')
                Board.display()
                break
        else:
            print("Invalid Move. Try Again")




play_game()




 | | 
-----
 | | 
-----
 | | 
-----


Player Turn: 
X| | 
-----
 | | 
-----
 | | 
-----


AI Turn: 
X| | 
-----
 |O| 
-----
 | | 
-----


Player Turn: 


ValueError: invalid literal for int() with base 10: ''

## Connect4

In [11]:
import numpy as np

class ConnectFour:
    def __init__(self):
        self.board = np.zeros((6, 7), dtype=int)

    def display_board(self):
        print(np.flip(self.board, 0))

    def is_valid_location(self, col):
        # return self.board[0][col] == 0
        return self.board[5][col] == 0

    def get_next_open_row(self, col):
        for r in range(6):
            if self.board[r][col] == 0:
                return r

    def drop_piece(self, row, col, piece):
        self.board[row][col] = piece

    def is_winner(self, piece):
        # Check horizontal locations for win
        for c in range(4):
            for r in range(6):
                if (self.board[r][c] == piece and self.board[r][c+1] == piece and 
                    self.board[r][c+2] == piece and self.board[r][c+3] == piece):
                    return True

        # Check vertical locations for win
        for c in range(7):
            for r in range(3):
                if (self.board[r][c] == piece and self.board[r+1][c] == piece and 
                    self.board[r+2][c] == piece and self.board[r+3][c] == piece):
                    return True

        # Check positively sloped diagonals
        for c in range(4):
            for r in range(3):
                if (self.board[r][c] == piece and self.board[r+1][c+1] == piece and 
                    self.board[r+2][c+2] == piece and self.board[r+3][c+3] == piece):
                    return True

        # Check negatively sloped diagonals
        for c in range(4):
            for r in range(3, 6):
                if (self.board[r][c] == piece and self.board[r-1][c+1] == piece and 
                    self.board[r-2][c+2] == piece and self.board[r-3][c+3] == piece):
                    return True

        return False

    def is_full(self):
        return not np.any(self.board == 0)

def alpha_beta_pruning(board, depth, alpha, beta, maximizing_player):
    if board.is_winner(1):
        return -1000000, None
    elif board.is_winner(2):
        return 1000000, None
    elif board.is_full() or depth == 0:
        return 0, None

    if maximizing_player:
        max_eval = float('-inf')
        best_move = None
        for col in range(7):
            if board.is_valid_location(col):
                row = board.get_next_open_row(col)
                board.drop_piece(row, col, 2)
                eval, _ = alpha_beta_pruning(board, depth-1, alpha, beta, False)
                board.board[row][col] = 0
                if eval > max_eval:
                    max_eval = eval
                    best_move = col
                alpha = max(alpha, eval)
                if alpha >= beta:
                    break
        return max_eval, best_move
    else:
        min_eval = float('inf')
        best_move = None
        for col in range(7):
            if board.is_valid_location(col):
                row = board.get_next_open_row(col)
                board.drop_piece(row, col, 1)
                eval, _ = alpha_beta_pruning(board, depth-1, alpha, beta, True)
                board.board[row][col] = 0
                if eval < min_eval:
                    min_eval = eval
                    best_move = col
                beta = min(beta, eval)
                if alpha >= beta:
                    break
        return min_eval, best_move

def play_game():
    game = ConnectFour()
    game_over = False
    turn = 0

    while not game_over:
        game.display_board()
        if turn == 0:
            col = int(input("Player 1 make your move (0-6): "))
            if game.is_valid_location(col):
                row = game.get_next_open_row(col)
                game.drop_piece(row, col, 1)
                if game.is_winner(1):
                    game.display_board()
                    print("Player 1 wins!")
                    game_over = True
        else:
            _, col = alpha_beta_pruning(game, 5, float('-inf'), float('inf'), True)
            if game.is_valid_location(col):
                row = game.get_next_open_row(col)
                game.drop_piece(row, col, 2)
                if game.is_winner(2):
                    game.display_board()
                    print("Player 2 (AI) wins!")
                    game_over = True

        turn += 1
        turn = turn % 2

if __name__ == "__main__":
    play_game()


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
[[2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 1 0 0 0 0 0]]
[[2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [1 1 0 0 0 0 0]]
[[2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 2

ValueError: invalid literal for int() with base 10: ''

In [38]:
class Connect4:

    def __init__(self):

        self.board = [ [0 for _ in range(6)] for _ in range(6) ]


    def display(self):

        for i in range(6):
            for j in range(6):
                print( self.board[i][j], end=' ' )
            print()
        print()
        print()

    
    def is_winner(self, player=1):

        # row
        for i in range(6):
            for j in range(3):
                if ( self.board[i][j] == player and self.board[i][j+1] == player and self.board[i][j+2] == player and self.board[i][j+3] == player):
                    return True

        # col
        for i in range(3):
            for j in range(6):
                if ( self.board[i][j] == player and self.board[i+1][j] == player and self.board[i+2][j] == player and self.board[i+3][j] == player):
                    return True
        
        # LD
        for i in range(3):
            for j in range(3):
                if ( self.board[i][j] == player and self.board[i+1][j+1] == player and self.board[i+2][j+2] == player and self.board[i+3][j+3] == player):
                    return True
        
        # RD
        for i in range(3):
            for j in range(3, 6):
                if ( self.board[i][j] == player and self.board[i+1][j-1] == player and self.board[i+2][j-2] == player and self.board[i+3][j-3] == player):
                    return True
        
        return False

    
    def is_valid_location(self, col):

        return self.board[0][col] == 0

    
    def get_next_open_row(self, col):

        for i in range(5, -1, -1):
            if self.board[i][col] == 0:
                return i

    
    def drop_piece(self, row, col, player):

        self.board[row][col] = player

    
    def clear_position(self, row, col):

        self.board[row][col] = 0

    
    def is_full(self):

        for i in range(6):
            for j in range(6):
                if self.board[i][j] == 0:
                    return False
        return True



def AlphaBetaPruning(board, depth, alpha, beta, maximizing):

    if board.is_winner(1):
        return -1000000 , None
    elif board.is_winner(2):
        return 1000000 , None
    elif board.is_full() or depth == 0:
        return 0, None

    if maximizing:

        max_eval = float('-inf')
        best_move = None

        for i in range(6):
            for c in range(6):
                if board.is_valid_location(c):
                    r = board.get_next_open_row(c)
                    board.drop_piece(r, c, 2)
                    eval, _ = AlphaBetaPruning(board, depth-1, alpha, beta, False)
                    board.clear_position(r, c)

                    if (eval > max_eval):
                        max_eval = eval
                        best_move = c

                    alpha = max(eval, alpha)
                    if alpha >= beta:
                        break
        return max_eval, best_move
    
    else:
        
        min_eval = float('inf')
        best_move = None

        for i in range(6):
            for c in range(6):
                if board.is_valid_location(c):
                    r = board.get_next_open_row(c)
                    board.drop_piece(r, c, 1)
                    eval, _ = AlphaBetaPruning(board, depth-1, alpha, beta, False)
                    board.clear_position(r, c)

                    if (eval < min_eval):
                        min_eval = eval
                        best_move = c

                    beta = min(eval, beta)
                    if alpha >= beta:
                        break
        return min_eval, best_move


    



def play_game():

    game = Connect4()
    turn = 0
    game_over = False

    while not game_over:

        game.display()

        if turn:
            print("AI Turn")
            player = 2
            _, col = AlphaBetaPruning(game, 5, float('-inf'), float('inf'), True) # Look only 5 steps ahead. needed to decrease number of branchings

            if game.is_valid_location(col):
                row = game.get_next_open_row(col)
                game.drop_piece(row, col, player)

                if game.is_winner(player):
                    print("AI Won")
                    game_over = True

            


        else:
            print("Player Turn")
            player = 1
            col = int(input("Enter Col: "))

            if game.is_valid_location(col):
                row = game.get_next_open_row(col)
                game.drop_piece(row, col, player)

                if game.is_winner(player):
                    print("Player Won")
                    game_over = True

        turn += 1
        turn = turn % 2








play_game()

0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 


Player Turn
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
1 0 0 0 0 0 


AI Turn
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
2 0 0 0 0 0 
1 0 0 0 0 0 


Player Turn
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
1 0 0 0 0 0 
2 0 0 0 0 0 
1 0 0 0 0 0 


AI Turn
0 0 0 0 0 0 
0 0 0 0 0 0 
2 0 0 0 0 0 
1 0 0 0 0 0 
2 0 0 0 0 0 
1 0 0 0 0 0 


Player Turn


ValueError: invalid literal for int() with base 10: ''